
export const projectsData = [
  {
    title: "Suraksha-AI",
    shortDescription: "Smart Surveillance System",
    description: "An intelligent surveillance security system using YOLO and real-time video processing.",
    longDescription:
      "Suraksha-AI is a smart surveillance system leveraging YOLO v11 and real-time video analytics to enhance security. It detects threats with high accuracy and reduces false positives through advanced filtering techniques.",
    logo: "/suraksha.png",
    image: "/suraksha.png",
    featured: true,
    techStack: ["Flask", "Python", "YOLO v11", "Firebase", "Ultralytics"],
    demoLink: null,
    sourceLink: "https://github.com/sahabji0P/Enhancing-Home-Security",
    features: [
      "Real-time object detection and threat analysis",
      "High-accuracy YOLO-based AI model",
      "Custom data augmentation for improved detection",
      "Optimized for real-time performance with reduced false positives",
      "Custom Chat Bot, that is trained on the log that is generated by the system",
    ],
    challenges:
      "Optimizing YOLO v11 for real-time inference while maintaining high accuracy and reducing computational overhead.",
  },
  {
    title: "Recycle Bin",
    shortDescription: "Waste Management Platform",
    description: "A marketplace connecting buyers and sellers of recyclable materials with real-time analytics.",
    longDescription:
      "Recycle Bin is a web platform facilitating the trade of recyclable materials. It features real-time sales analytics, interactive dashboards, and optimized buyer-seller interactions.",
    logo: "/recyclebin.jpeg",
    image: "/recyclebin.jpeg",
    featured: false,
    techStack: ["Next.js", "MongoDB", "Postman", "Chart.js"],
    demoLink: "#",
    sourceLink: "https://github.com/sahabji0P/recycle-bin",
    features: [
      "Intuitive marketplace for recyclables",
      "Real-time transaction analytics",
      "Seller dashboard with interactive charts",
      "Optimized transaction flow reducing time by 25%",
    ],
    challenges:
      "Building a seamless buyer-seller interaction system while ensuring scalability and data accuracy.",
  },
  {
    title: "Khel Onn",
    shortDescription: "Sports Event Management App",
    description: "An Android application for managing sports events, scores, and schedules.",
    longDescription:
      "Khel Onn provides a platform for users to register for sports events, view live scores, and manage schedules efficiently. The app reduces information delays by 40% and enhances user experience with real-time updates by pushing out notifications.",
    logo: "/khelon.png",
    image: "/khelon.png",
    featured: false,
    techStack: ["Java", "XML", "Firebase", "Android Studio"],
    demoLink: "#",
    sourceLink: "https://github.com/sahabji0P/KhelOn",
    features: [
      "User registration and event management",
      "Real-time score updates and news",
      "Optimized scheduling system reducing conflicts",
      "University's Sports Social Application",
    ],
    challenges:
      "Ensuring real-time score updates and smooth user experience with minimal latency.",
  },
];
